# Generated by Django 4.1.13 on 2024-02-02 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bordado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Tamanho', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG')], max_length=2)),
                ('Quantidade', models.PositiveIntegerField(default=0)),
                ('Status', models.CharField(choices=[('Na Loja', 'Na Loja'), ('Bordando', 'Bordando'), ('Pronto', 'Pronto')], max_length=20)),
                ('Data', models.DateTimeField(default='2024-02-02 02:04', editable=False)),
                ('Telefone', models.CharField(help_text='Informe apenas DDD e número (ex: 11987654321)', max_length=15)),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por')),
            ],
        ),
    ]
