# Generated by Django 4.1.13 on 2024-02-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordado',
            name='Data',
            field=models.DateTimeField(default='2024-02-02 02:08', editable=False),
        ),
        migrations.AlterField(
            model_name='bordado',
            name='Telefone',
            field=models.CharField(max_length=15),
        ),
    ]
