# Generated by Django 4.1.13 on 2024-02-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordados', '0002_alter_bordado_data_alter_bordado_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordado',
            name='Data',
            field=models.DateTimeField(default='2024-02-02 02:29', editable=False),
        ),
    ]
